---
version: "3.5"

includes:
  taskotter:
    taskfile: taskfiles/Taskfile.yml
tasks:
  ci:
    desc: Run CI checks
    cmds:
      - task: taskotter:go:fmt:check
      - task: taskotter:lint

  ci:fix:
    desc: Run CI fixs
    cmds:
      - task: taskotter:go:fmt
      - task: taskotter:lint:fix
