---
name: TaskOtter
on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * 1
permissions:
  contents: write
  pull-requests: write
jobs:
  taskotter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: TaskOtter
        id: taskotter
        uses: ./
        with:
          github-token: ${{ github.token }}
          tasks: |
            eslint
            prettier
            typescript
            go
          js: |
            runtime: nodejs
            package-manager: pnpm
          includes-doc: true
          target-folder: taskfiles
      - name: Print result
        shell: bash
        env:
          TASKOTTER_CHANGED: ${{ steps.taskotter.outputs.changed }}
          TASKOTTER_SOURCE_SHA: ${{ steps.taskotter.outputs.source-sha }}
          TASKOTTER_PULL_REQUEST_URL: ${{ steps.taskotter.outputs.pull-request-url }}
        run: |-
          echo "Changed: ${TASKOTTER_CHANGED}"
          echo "Source SHA: ${TASKOTTER_SOURCE_SHA}"
          echo "Pull request: ${TASKOTTER_PULL_REQUEST_URL}"
