---
name: Test TaskOtter
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  itself:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Run TaskOtter
        id: taskotter
        uses: ./.github/actions/itself
        with:
          github-token: ${{ github.token }}
          fail-on-changes: true
          store-version: v0.0.12
          tasks: |
            go
            go-junit-report
            golangci-lint
            yamllint
            yamlfix
            actionlint
            zizmor
            adrs
            hadolint
          includes-doc: true
          target-folder: taskotter

      - name: Print result
        if: always()
        shell: bash
        env:
          TASKOTTER_CHANGED: ${{ steps.taskotter.outputs.changed }}
          TASKOTTER_SOURCE_SHA: ${{ steps.taskotter.outputs.source-sha }}
          TASKOTTER_PULL_REQUEST_URL: ${{ steps.taskotter.outputs.pull-request-url }}
        run: |
          echo "Changed: ${TASKOTTER_CHANGED}"
          echo "Source SHA: ${TASKOTTER_SOURCE_SHA}"
          echo "Pull request: ${TASKOTTER_PULL_REQUEST_URL}"

  ci:
    runs-on: ubuntu-latest
    needs: itself
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Run CI
        uses: ./.github/actions/ci

  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Run CodSpeed
        uses: ./.github/actions/codspeed
